spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc://localhost:3306/temp_website_display?serverTimezone=Hongkong
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: 1000

mybatis:
  type-aliases-package: cn.edu.gdufs.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 该项目相关的配置属性（自行修改）
my-config:
  # 文件上传存放的路径
  file-upload-path: "F:\\A\\"